version: '3.8'
 
services:
 elasticsearch:
   build:
     context: elasticsearch/
   ports:
     - "9200:9200"
     - "9300:9300"
   environment:
     ES_JAVA_OPTS: "-Xmx256m -Xms256m"
     ELASTIC_PASSWORD: elastic123
     discovery.type: single-node
   networks:
     - elk_stack
   volumes:
     - elastic_vol:/usr/share/elasticsearch/data

 logstash:
   build:
     context: logstash/
   ports:
     - "5000:5000"
     - "7600:7600"
   environment:
     LS_JAVA_OPTS: "-Xmx256m -Xms256m"
   networks:
     - elk_stack
   depends_on:
     - elasticsearch
 
 kibana:
   build:
     context: kibana/
   ports:
     - "5601:5601"
   networks:
     - elk_stack
   depends_on:
     - elasticsearch
 
networks:
 elk_stack:
   driver: bridge
 
volumes:
 elastic_vol:
   external: true
